server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: znew
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      fail-on-empty-beans: false
  datasource:
    hikari:
      minimum-idle: 10 # 连接池中允许的最小连接数。缺省值：10
      maximum-pool-size: 20 # 连接池中允许的最大连接数。缺省值：10
      auto-commit: true # 自动提交 默认值为 true
      idle-timeout: 600000 # 连接允许在池中闲置的最长时间，一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      max-lifetime: 1800000 # 一 个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      connection-timeout: 30000  # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-test-query: select 1 #连接测试查询语句，用于验证连接是否有效
      validation-timeout: 30000 #验证连接有效性的超时时间，单位为毫秒,默认值 5000 毫秒（5 秒）
      pool-name: mysql-pool # 连接池名字，用于日志和监控
  data:
    redis:
      lettuce:
        pool:
          max-active: 8 #连接池允许的最大连接数，默认为 8。
          max-wait: 30000 #连接池等待连接的最大时间，单位为毫秒，如果为 -1 则表示无限等待。
          max-idle: 8 #连接池允许的最大空闲连接数，默认为 8。
          min-idle: 0 #连接池允许的最小空闲连接数，默认为 0。
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:com/hfw/service/**/*Mapper.xml


  type-handlers-package: com.hfw.model.component
  configuration:
    map-underscore-to-camel-case: true #字段下划线映射驼峰命名
    default-enum-type-handler:  com.hfw.model.component.EnumCodeTypeHandler #枚举处理
    databaseId: PGSQL #xbatis数据库识别

upload:
  storage-path: C:\\tmp\\upload

gen:
  pack: com.hfw
  author: farkle
  path: D:\\tmp\\admin
  table-prefix: t_
  db: znew
  project-name: znew
  logic-delete-field: deleted

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 86400 #一天
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 1800 #30分钟
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  #is-share: false
  # 是否输出操作日志
  #is-log: true
  #maxLoginCount: 2
