spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.41.131:5432/znew?currentSchema=public&timezone=Asia/Shanghai&client_encoding=UTF8&sslmode=disable&reWriteBatchedInserts=true
    username: postgres
    password: postgres
  data:
    redis:
      host: 192.168.109.129
      port: 6379
      #password: 123456
      #database: 0
      timeout: 10000  # 连接超时时间（毫秒）

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl