server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/znew?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: 123456
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:com/hfw/service/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case=true: true #字段下划线映射驼峰命名
    default-enum-type-handler:  com.hfw.model.mapper.EnumCodeTypeHandler #枚举处理
    databaseId: MYSQL #xbatis数据库识别
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

upload:
  storage-path: D:\\tmp\\upload

gen:
  pack: com.hfw
  author: farkle
  path: D:\\tmp\\admin
  table-prefix: t_
  db: znew
  project-name: sys
  logic-delete-field: deleted

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 86400 #一天
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 1800 #30分钟
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  #is-share: false
  # 是否输出操作日志
  #is-log: true
  #maxLoginCount: 2
